version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    groups:
      babel-packages:
        patterns:
          - '@babel/*'
      eslint-packages:
        patterns:
          - '@eslint/compat'
          - '@eslint/eslintrc'
          - '@eslint/js'
          - 'eslint'
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - 'eslint-config-prettier'
          - 'eslint-plugin-*'
      jest-packages:
        patterns:
          - 'jest*'
          - 'babel-jest'
          - '@types/jest'
      react-packages:
        patterns:
          - 'react*'
          - '@testing-library/react'
  # Enable version updates for GitHub Actions used in the workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
