name: Test, Format and Create Docs
on: [push, pull_request]
jobs:
    check-repo:
        name: Auto Update Repo
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.REPO_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            
            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Prettify code
              run: npm run format

            - name: Commit Prettier
              uses: EndBug/add-and-commit@v9
              with:
                author_name: Prettier Action
                message: 'Update source files based on Prettier'

            - name: Generate docs
              run: npm run docs

            - name: Commit Prettier
              uses: EndBug/add-and-commit@v9
              with:
                author_name: TypeDocs Action
                message: 'Update docs based on TypeDocs'