name: Test, Format and Create Docs
on: [push, pull_request]
jobs:
    check-repo:
        name: Auto Update Repo
        runs-on: ubuntu-latest
        permissions:
          # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
          contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            
            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Prettify code
              run: npm run format

            - name: Commit Prettier
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Update source files based on Prettier

            - name: Generate docs
              run: npm run docs

            - name: Commit Prettier
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Update docs based on TypeDocs